__title__ = 'pinterest'
__description__ = 'Python Pinterest API'
__url__ = 'https://github.com/bryand1/python-pinterest-api'
__version__ = '0.0.6'
__author__ = 'Bryan Andrade'
__author_email__ = 'me@bryanandrade.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Bryan Andrade'
